AllCops:
  TargetRubyVersion: 3.2.2

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes

Style/Documentation:
    Enabled: false

Layout/LineLength:
  Max: 150

Metrics/MethodLength:
  Max: 20
