module HexletCode
  class Tag
    def self.build: -> String

    def self.paired_tag?: -> String

    def self.parsing_attributes: -> String
  end

  class FormBodyBuilder
    @result: String

    def input: -> String

    def submit: -> String
  end

  def self.form_for: -> String
end
